//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski.
        /// </summary>
        public static string BtnCRO {
            get {
                return ResourceManager.GetString("BtnCRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalje.
        /// </summary>
        public static string BtnDalje {
            get {
                return ResourceManager.GetString("BtnDalje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string BtnENG {
            get {
                return ResourceManager.GetString("BtnENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabrana velicina.
        /// </summary>
        public static string BtnOdabranaVelicina {
            get {
                return ResourceManager.GetString("BtnOdabranaVelicina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj:.
        /// </summary>
        public static string LblBroj {
            get {
                return ResourceManager.GetString("LblBroj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaćini.
        /// </summary>
        public static string LblDomacini {
            get {
                return ResourceManager.GetString("LblDomacini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabijeni golovi:.
        /// </summary>
        public static string LblGolovi {
            get {
                return ResourceManager.GetString("LblGolovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gosti.
        /// </summary>
        public static string LblGosti {
            get {
                return ResourceManager.GetString("LblGosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        public static string LblIme {
            get {
                return ResourceManager.GetString("LblIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite jezik aplikacije:.
        /// </summary>
        public static string LblJezikApp {
            get {
                return ResourceManager.GetString("LblJezikApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žuti kartoni:.
        /// </summary>
        public static string LblKartoni {
            get {
                return ResourceManager.GetString("LblKartoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA kod:.
        /// </summary>
        public static string LblKod {
            get {
                return ResourceManager.GetString("LblKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv:.
        /// </summary>
        public static string LblNaziv {
            get {
                return ResourceManager.GetString("LblNaziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj zabijenih / primljenih / razlika golova:.
        /// </summary>
        public static string LblOmjerGolova {
            get {
                return ResourceManager.GetString("LblOmjerGolova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pobjede / porazi / neodluceni :.
        /// </summary>
        public static string LblOmjeriUtakmica {
            get {
                return ResourceManager.GetString("LblOmjeriUtakmica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija:.
        /// </summary>
        public static string LblPozicija {
            get {
                return ResourceManager.GetString("LblPozicija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj odigranih utakmica:.
        /// </summary>
        public static string LblUtakmice {
            get {
                return ResourceManager.GetString("LblUtakmice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite način prikaza glavnog prozora:.
        /// </summary>
        public static string LblVelicina {
            get {
                return ResourceManager.GetString("LblVelicina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string MainWindow_Naslov {
            get {
                return ResourceManager.GetString("MainWindow_Naslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utakmica.
        /// </summary>
        public static string OdabirRep_Naslov {
            get {
                return ResourceManager.GetString("OdabirRep_Naslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string Postavke {
            get {
                return ResourceManager.GetString("Postavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentacija.
        /// </summary>
        public static string PregledRep_Naslov {
            get {
                return ResourceManager.GetString("PregledRep_Naslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igrač.
        /// </summary>
        public static string PrikazIgraca_Naslov {
            get {
                return ResourceManager.GetString("PrikazIgraca_Naslov", resourceCulture);
            }
        }
    }
}
